module.exports = {
    SCENTS: ['VANILLA', 'LAVENDER', 'NEW_CAR', 'OCEAN_BREEZE'],
    SERVICE_CATEGORIES: ['EXPRESS', 'BASIC', 'PREMIUM', 'COMPLETE', 'ULTIMATE'],
    BOOKING_STATUSES: ['PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED']
  };